version: '3.4'

services:
  picsearchapi:
    environment:
      - POSTGRES_DB_PASSWORD=11111111
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "6000:80"
      - "6001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - 

  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "80:80" 
